# Generated by Django 2.2 on 2019-05-04 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False, verbose_name='作者编号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='作者')),
                ('author_image', models.ImageField(default='', max_length=200, upload_to='book/authorImage/', verbose_name='作者图片')),
                ('intro', models.TextField(verbose_name='作者介绍')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='书籍编号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='书名')),
                ('cover_image', models.ImageField(max_length=200, upload_to='book/coverImage/', verbose_name='封面图')),
                ('pub_time', models.DateField(blank=True, null=True, verbose_name='出版时间')),
                ('intro', models.TextField(verbose_name='图书介绍')),
                ('labal', models.CharField(default='', max_length=20, verbose_name='标签')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='推荐')),
                ('editors_id', models.CharField(max_length=30, verbose_name='再创作者')),
                ('is_new', models.BooleanField(default=False, verbose_name='最新')),
                ('authors', models.ManyToManyField(to='books.Authors', verbose_name='作者')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False, verbose_name='章节编号')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='章节名')),
                ('pub_time', models.DateField(verbose_name='出版时间')),
                ('article', models.TextField(verbose_name='章节内容')),
                ('analyze', models.TextField(verbose_name='解析')),
                ('like_num', models.IntegerField(default='0', verbose_name='点赞数')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否读过')),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='this_chapter_from_this_book', to='books.Books', verbose_name='所属书籍')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='ChapterComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creare_time', models.DateTimeField(auto_now_add=True)),
                ('comment_word', models.TextField(verbose_name='评论内容')),
                ('like_num', models.IntegerField(default='0', verbose_name='点赞数')),
                ('comment_chapter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_this_chapter', to='books.Chapters', verbose_name='章节评论')),
            ],
            options={
                'verbose_name': '章节评论',
                'verbose_name_plural': '章节评论',
            },
        ),
        migrations.CreateModel(
            name='BookComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creare_time', models.DateTimeField(auto_now_add=True)),
                ('comment_word', models.TextField(verbose_name='评论内容')),
                ('like_num', models.IntegerField(default='0', verbose_name='点赞数')),
                ('comment_book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_this_book', to='books.Books', verbose_name='图书评论')),
            ],
            options={
                'verbose_name': '书评',
                'verbose_name_plural': '书评',
            },
        ),
    ]
