# Generated by Django 2.2 on 2019-05-04 05:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='analyze',
            field=ckeditor.fields.RichTextField(verbose_name='解析'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='article',
            field=ckeditor.fields.RichTextField(verbose_name='章节内容'),
        ),
    ]
