# Generated by Django 2.2 on 2019-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_rich_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='rich_text',
        ),
        migrations.AddField(
            model_name='books',
            name='book_type',
            field=models.IntegerField(choices=[(1, '文学'), (2, '世界文学'), (3, '童话故事'), (4, '古典名著'), (5, '中外双语')], default='1', verbose_name='分类'),
        ),
    ]
