# Generated by Django 2.2 on 2019-05-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookcomments_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomments',
            name='comment_comment',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_this_comment', to='books.BookComments', verbose_name='评论评论'),
        ),
    ]
