# Generated by Django 2.2 on 2019-05-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190514_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='扩展内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='相关图片')),
                ('chapter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.Chapters', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '章节拓展',
                'verbose_name_plural': '章节拓展',
            },
        ),
    ]
