# Generated by Django 2.2 on 2019-05-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_expand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='analyze',
        ),
    ]
