# Generated by Django 2.2 on 2019-05-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_expand_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptercomments',
            name='comment_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='评论图片'),
        ),
    ]
