# Generated by Django 2.2 on 2019-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_chaptercomments_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='time',
            field=models.CharField(default='', max_length=50, verbose_name='生卒年'),
        ),
        migrations.AlterField(
            model_name='chaptercomments',
            name='comment_image',
            field=models.ImageField(blank=True, null=True, upload_to='book/chapterCommentImages', verbose_name='评论图片'),
        ),
        migrations.AlterField(
            model_name='expand',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='扩展内容'),
        ),
        migrations.AlterField(
            model_name='expand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/chapterExpandImages', verbose_name='相关图片'),
        ),
    ]
