# Generated by Django 2.2 on 2019-05-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20190530_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=300, verbose_name='时间点')),
                ('title', models.CharField(default='', max_length=30, verbose_name='标题')),
                ('intro', models.TextField(verbose_name='内容')),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='this_timeline_from_this_book', to='books.Books', verbose_name='所属书籍')),
            ],
            options={
                'verbose_name': '时间线',
                'verbose_name_plural': '时间线',
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='姓名')),
                ('title', models.CharField(default='', max_length=30, verbose_name='标题')),
                ('intro', models.TextField(verbose_name='内容')),
                ('book', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='this_characters_from_this_book', to='books.Books', verbose_name='所属书籍')),
            ],
            options={
                'verbose_name': '人物志',
                'verbose_name_plural': '人物志',
            },
        ),
    ]
