# Generated by Django 2.2 on 2019-05-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_characters_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/charactersImages', verbose_name='相关图片'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/timelineImages', verbose_name='相关图片'),
        ),
    ]
