# Generated by Django 2.2 on 2019-05-07 02:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_books_rich_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFellback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, verbose_name='反馈内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
            },
        ),
        migrations.CreateModel(
            name='userFavBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间  ')),
                ('books', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.Books', verbose_name='图书 ')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户书架',
                'verbose_name_plural': '用户书架',
            },
        ),
        migrations.CreateModel(
            name='userCommentChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_word', models.CharField(max_length=300, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('chapter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.Chapters', verbose_name='章节')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户章节评论',
                'verbose_name_plural': '用户章节评论',
            },
        ),
        migrations.CreateModel(
            name='userCommentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_word', models.CharField(max_length=300, verbose_name='评论内容')),
                ('score', models.PositiveSmallIntegerField(verbose_name='评分')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间  ')),
                ('books', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.Books', verbose_name='图书')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户书评',
                'verbose_name_plural': '用户书评',
            },
        ),
    ]
