# Generated by Django 2.2 on 2019-05-07 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_rich_text'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavbook',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.RemoveField(
            model_name='userfavbook',
            name='books',
        ),
        migrations.AddField(
            model_name='userfavbook',
            name='books',
            field=models.ManyToManyField(default='', to='books.Books', verbose_name='图书 '),
        ),
    ]
