# Generated by Django 2.2 on 2019-05-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_rich_text'),
        ('operation', '0002_auto_20190507_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfellback',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='小程序评分'),
        ),
        migrations.AlterField(
            model_name='usercommentbook',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='评分'),
        ),
        migrations.RemoveField(
            model_name='userfavbook',
            name='books',
        ),
        migrations.AddField(
            model_name='userfavbook',
            name='books',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.Books', verbose_name='图书 '),
        ),
    ]
