# Generated by Django 2.2 on 2019-05-08 04:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_books_rich_text'),
        ('operation', '0003_auto_20190507_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavbook',
            unique_together={('user', 'books')},
        ),
    ]
