# Generated by Django 2.2 on 2019-05-11 01:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20190507_1030'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_auto_20190508_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='userLikeCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('circle', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='circles.Circles', verbose_name='畅想圈')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户点赞畅想圈',
                'verbose_name_plural': '用户点赞畅想圈',
            },
        ),
    ]
