# Generated by Django 2.2 on 2019-05-04 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circles',
            fields=[
                ('circle_id', models.AutoField(primary_key=True, serialize=False, verbose_name='畅想编号')),
                ('creare_time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('desc', models.TextField(default='', verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='circle/images/', verbose_name='图片')),
                ('like_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
            ],
            options={
                'verbose_name': '畅想圈',
                'verbose_name_plural': '畅想圈',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creare_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('comment_word', models.TextField(verbose_name='评论内容')),
                ('like_num', models.IntegerField(default='0', verbose_name='点赞数')),
                ('comment_chapter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_this_circle', to='circles.Circles', verbose_name='动态评论')),
            ],
            options={
                'verbose_name': '畅想圈评论',
                'verbose_name_plural': '畅想圈评论',
            },
        ),
    ]
